apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-api
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hospital-api
  template:
    metadata:
      labels:
        app: hospital-api
    spec:
      containers:
      - name: hospital-api
        image: 283904064984.dkr.ecr.eu-north-1.amazonaws.com/shivam-hospital-api:latest
        ports:
        - containerPort: 4451
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "4451"
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/hms"
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: CORS_ORIGINS
          value: "https://vasavicafe.shop,https://www.vasavicafe.shop"
        - name: AWS_REGION
          value: "eu-north-1"
---
apiVersion: v1
kind: Service
metadata:
  name: hospital-api-service
  namespace: backend
spec:
  selector:
    app: hospital-api
  ports:
  - port: 8000
    targetPort: 4451
