apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shivam-hospital-ingress
  namespace: backend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - vasavicafe.shop
    - www.vasavicafe.shop
    secretName: vasavicafe-tls
  rules:
  - host: vasavicafe.shop
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: hospital-api-service
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 8000
  - host: www.vasavicafe.shop
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: hospital-api-service
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 8000
